# Be sure to restart your server when you modify this file.

# Your secret key is used for verifying the integrity of signed cookies.
# If you change this key, all old signed cookies will become invalid!

# Make sure the secret is at least 30 characters and all random,
# no regular words or you'll be exposed to dictionary attacks.
# You can use `rake secret` to generate a secure secret key.

# Make sure the secrets in this file are kept private
# if you're sharing your code publicly.

development:
  secret_key_base: e94bcddeea48c580f7db2c82d57e6ee29d4983522121226484a5dd3b76dfeaa1a3a5ac59e6e72557f71ff330a9f53a8b9ef6768af4e94a83da21ab24a868bc79

test:
  secret_key_base: 83368061d19f29d83fcd554a0894a7bc337cf85666dc99b4b2f06d77115cb0e449aab1dc3e2aba1523e1d6133db6d364b556ed5349f23b011bd3cacfa2bb630c

# Do not keep production secrets in the repository,
# instead read values from the environment.
production:
  secret_key_base: <%= ENV["SECRET_KEY_BASE"] %>
